### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by wxgkuaile** [gfreund123/cfil#1]
I changed the script to run one environment at a time because I don't have enough GPUs, but when I finished running the HalfCheetah environment and started running the Ant environment there was a bug:

Traceback (most recent call last):
  File "rewarder.py", line 418, in <module>
    run_bc_rl_experiment(rewarder_args=rewarder_args, flow_type=flow_type, flow_args=flow_args, **args_dict)
  File "rewarder.py", line 313, in run_bc_rl_experiment
    expert_train_data = torch.from_numpy(expert_replay_buffer.data).to(device)
RuntimeError: CUDA error: out of memory

My question is when I clear the cache does it affect the performance of the experiment? Does it need to re-capture the data from the expert to put it into the buffer pool, I mean the way to clear the cache is just a little bit longer at run time.

Here is the code I want to clear the cache:
import gc
gc.collect()
torch.cuda.empty_cache()

Here's the script I adapted：
#! /bin/bash

env_name=$1

for((seed=1;seed<=4;seed+=1))
do

if [ $env_name = "Humanoid-v2" ]; then
    data_set="Spinningup"
else
    data_set="Value_Dice"
fi

python rewarder.py --rewarder_type 'coupledflow' --env_name ${env_name} --seed $seed --use_tanh --tanh_scale 15 6 --title "seed$seed" --outputdir 'standard_setting_tanh_15_6_reg1_smooth05' --num_train_trajs 1 --start_steps 2000 --tanh_shift --flow_norm 'none' --data_set_name $data_set --smooth 0.5 --flow_reg &

python rewarder.py --rewarder_type 'coupledflow' --env_name ${env_name} --seed $seed --use_tanh --tanh_scale 15 6 --title "state_only_seed$seed" --outputdir 'state_only_tanh_15_6_reg1_smooth05' --num_train_trajs 1 --start_steps 2000 --tanh_shift --flow_norm 'none' --data_set_name $data_set --smooth 0.5 --flow_reg  --option 0&

python rewarder.py --rewarder_type 'coupledflow' --env_name ${env_name} --seed $seed --use_tanh --tanh_scale 15 6 --title "state_next_state_seed$seed" --outputdir 'state_next_state_tanh_15_6_reg1_smooth05' --num_train_trajs 1 --start_steps 2000 --tanh_shift --flow_norm 'none' --data_set_name $data_set --smooth 0.5 --flow_reg  --option 2&

done

**Comment by gfreund123** [comment]
Hey, just a few questions to clarify:
1) You're running 5 concurrent seeds of the Ant environment right?
2) How much GPU RAM do you have? 
3) After how many of the 5 runs is the GPU out of memory?
4) Can you please clarify when exactly you're proposing to clear the cache?

The Ant's state and action spaces are larger then Half-Cheetahs so naturally it will require more memory (but It shouldn't be drastic or even too noticeable really). 

One solution to save some memory may be to remove the _.to(device)_ from line 313 in run_bc_rl_experiment, since each batch will anyways be moved onto the device in the update function.

**Comment by wxgkuaile** [comment]
Yes, at the same time. The RAM is 16280mib.Just a few hours ago I cleared the memory and now that the experiment is running and using 8760mib/16280mib, I added the clearing code to the main function of rewarder.py:
if __name__== '__main__'.
...
...
torch.cuda.empty_cache() #clear the cache is here.

if args.flow_norm == None.
        if args.env_name == 'Walker2d-v2': ... torch.cuda.empty_cache()
            flow_norm = 'none' 
        elif args.env_name == 'HalfCheetah-v2': flow_norm = 'none'
            flow_norm = 'none'
        elif args.env_name == 'Hopper-v2': flow_norm = 'none'
            flow_norm = 'none'
        elif args.env_name == 'Ant-v2': flow_norm = 'none'.
            flow_norm = 'none'
        elif args.env_name == 'Humanoid-v2': flow_norm = 'none': flow_norm = 'none'
            flow_norm = 'none'
...
...

It's currently running and we'll see if there's any impact when it's over, and finally thanks for your reply!

**Comment by gfreund123** [comment]
Ok so clearing the cache that way shouldn't have any affect on the experiment. To be honest though, I'm not sure what's being cleared. I mean given it's the start of a new python process, I'd expect the process's GPU cache to be empty (and _torch.cuda.empty_cache_ should only be affecting the cache of the current process).

Anyways, happy it's working. Let me know if results match and I will close the issue.

**Comment by wxgkuaile** [comment]
Thanks a lot, I just ran through and plotted the return, it looks pretty much the same as in your paper, problem solved, it works, you can turn it off.

**Comment by gfreund123** [comment]
Fantastic! Closing the issue.
